services:
    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        container_name: php
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./database:/var/www/database # Volume do SQLite
            - dbdump:/var/mysqldump/
            - /var/sftp:/var/sftp

    webserver:
        image: nginx:stable-alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

volumes:
    dbdump:
